### ISSUE TITLE
Feature: Lockitron/MyQ

### ISSUE THREAD

**Issue by identd113** [hjdhjd/homebridge-myq#101]
I have a Lockitron lock, which was acquired my LiftMaster, and added to the MyQ system a year or so ago.
When I load homebridge, this is what I see.

[8/16/2020, 10:28:19 AM] [myQ] Initializing myQ platform...
[8/16/2020, 10:28:19 AM] [myQ] myQ API: Successfully connected to the myQ API.
[8/16/2020, 10:28:20 AM] [myQ] myQ API: Discovered device family gateway: myQ hub (serial number: GW26000XXXXX).

I have the bridge, but not the hardware homebridge hub.
I would be happy to help where I can

**Comment by hjdhjd** [comment]
@identd113 I'd love to work with you on this and see what we can figure out. Can you start by explaining your physical myQ setup? What devices do you have (besides the Lockitron)? How do you control them (the myQ app?). Screenshots would be helpful since I don't have a Lockitron to experiment with.

**Comment by identd113** [comment]
I have a Lockitron Lock, and MYQ-G0301-E hub.  I have no other myQ devices on my account

**Comment by identd113** [comment]
![IMG_0572](https://user-images.githubusercontent.com/2689287/90570381-2831d880-e175-11ea-96db-ccf035e7813e.PNG)
![IMG_0571](https://user-images.githubusercontent.com/2689287/90570384-29fb9c00-e175-11ea-9a13-b0e3358f09f4.PNG)
![IMG_0570](https://user-images.githubusercontent.com/2689287/90570386-2a943280-e175-11ea-9c3a-41ea4afd6f86.PNG)

**Comment by identd113** [comment]
Is there any other data I can provide?
If I try to access the myq ios app via a charles proxy, I am not able to authticate

**Comment by hjdhjd** [comment]
@identd113 You won't be able to reverse engineer things that way due to certificate pinning...essentially a security feature designed to prevent what you're doing. To reverse engineer it, someone will need to disable certificate pinning (probably on an Android device because it's easier to get access to the filesystem), and then we can take it from there. If there's a webUI that works...that would be a great starting point. Is there one?

@iRayanKhan I'd love to collaborate! It's a tough problem to crack...we need more devices and people willing to test / break things. :smile:

**Comment by xozai** [comment]
I am willing to test.  I have a lockitron + MyQ hub.

**Comment by hjdhjd** [comment]
Thanks guys. Liftmaster / Chamberlain has systematically shutdown all API access to things like Lockitron. We're now faced with the prospect of reverse engineering a pretty uphill battle. If you look at some of the other open source home automation solutions out there...pretty much everyone has retired Lockitron integration from July 2020 onward.

While you can use the myQ **app** to access Lockitron, it doesn't use the myQ **API** to do it. When we access the myQ API, it doesn't even show knowledge of locks (Lockitron or otherwise). The app is using some other API aside from the one we know about to access the lock.

How to access it ourselves? Well...you need someone who is knowledgable in the Android world (because apps are easier to access / reverse engineer), and who knows how to bypass certificate pinning.

Certificate pinning is a security mechanism that prevents us from using SSL proxies to snoop the traffic that's occurring between the myQ app and the server endpoints. On the plus side, there are well-known ways that would be inappropriate to discuss here to disable certificate pinning directly in the app binaries, and then snoop the traffic. 

I don't have the access to the above to do it...and even if I did, I truly don't feel comfortable with my own knowledge base to effectively reverse engineer a binary. Give me an API or a pointer to an API I can begin to access, and then I can do something with it. Short of that, I don't think Lockitron support is going to happen anytime in the near future.

It's a lot of work...I'm happy to do the API implementation component, but someone needs to get us to that point.

It's unfortunate that it's undocumented, **and** that Chamberlain / Liftmaster is actively shutting down all the existing (known) API endpoints...but it's unfortunately where we are.

There are lots of good HomeKit-native lock options out there. I know that's little consolation to those that spent the money on the Lockitron ecosystem, but those are the challenges in being on the early end of the maturity of the  home automation hardware market.

**Comment by dppeak** [comment]
So, there's a tool that we often use on the mac to intercept the call from apps we developing on iOS.  It's Charles (https://www.charlesproxy.com) and it allows you to install a profile on your iPhone and set Charles on your Mac as a proxy.  You can then view the https calls that are being made.  This might be a good way for you to do some reverse engineering to find the Lockitron calls.

**Comment by hjdhjd** [comment]
It won’t work because of certificate pinning. See what I wrote above - I’m very familiar with Charles and the other man-in-the-middle proxies. You need to bypass certificate pinning in order to do anything useful.

**Comment by identd113** [comment]
Would something like this work?
https://github.com/nabla-c0d3/ssl-kill-switch2

**Comment by pponce** [comment]
That does sound like something that would help. Just need a jail broken device to test it out.

**Comment by hjdhjd** [comment]
"Just". Funny. :smile: Yes, is the short answer...your better bet would be to try something like that on Android. If someone wants to take that on, we can work to reverse engineer the API from there.

**Comment by pponce** [comment]
Wish I had the skills but I’ve never reverse engineered anything before.....
Hope someone is willing to give it a go.
Wish chamberlain would just move it over to the same api’s as the garage door.

**Comment by hjdhjd** [comment]
I would definitely not hold my breath for that, I'm afraid. The myQ API is a pretty fragile beast as it is. When it works, it's great...when it doesn't, it's atrocious. Given the acquisition was completed a year and a half ago, I bet we'll see some new products in 2021/2022 that will give all of us some insight into the direction they're going.

The one thing that's certain: Liftmaster / Chamberlain has been systematically removing access to all things Lockitron this year, and eliminating methods to access myQ (there used to be a myQ webUI you could log into, for example). So...either they're rebuilding and retrenching for the future, or something completely new is in the offing. Time will tell.

In the meantime, we get to enjoy what we have...

**Comment by hjdhjd** [comment]
To illustrate my point:


![](https://user-images.githubusercontent.com/4991612/85090684-ba3c5580-b1b3-11ea-9c26-cb057d5c9ff6.png)
