### ISSUE TITLE
Node 17 required on latest update - but I'm running the latest stable node for homebridge on pi which is v18.16

### ISSUE THREAD

**Issue by gleep52** [hjdhjd/homebridge-myq#1062]
**Describe The Problem:**

I updated my node version to 18.16 using the hb-service update-node command.  This plugin says it only works with 17+, and I'm now running 18.16 instead of 16.16.0... This plugin doesn't seem to properly detect what version of Node I have installed perhaps?
**To Reproduce:**

Have homebridge installed on a pi4 with node version 16.16.0 installed
Update node using "sudo hb-service update-node" 
reboot
Plugin will still report the version of node is not met yet.
**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 1.6.0 
* **Node Version:** v18.16.0
* **Homebridge-myQ Plugin Version**: 2.9.0
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone 16.4.1 | tVOS 16.4
* **Operating System and OS Version:** Raspbian GNU/Linux Buster (10)

**Comment by hjdhjd** [comment]
This isn’t a plugin issue. Homebridge is responsible for reporting out on issues with versions of Node, not HBUP. We simply are informing you that Node 16 isn’t going to be supported for much longer. 

Appreciate the report, but would direct you to Homebridge bug reporting rather than HBUP. That said - I don’t think either is the issue…Homebridge will tell you at startup what version of Node it’s using. You might want to carefully review the logs to see that it’s in fact using Node 18 rather than 16.

Best of luck.
