### ISSUE TITLE
429 - Too Many Requests

### ISSUE THREAD

**Issue by sir-captainmorgan21** [hjdhjd/homebridge-myq#1128]
**Describe The Problem:**
I noticed my commands from HomeKit to open/close the garage stopped working, so I checked my MyQ plugin and saw that there was an update available. I've updated it, and in the logs I see a constant output of the following error:

```
myQ API error: Temporary myQ API server-side issues encountered: 429 - Too Many Requests. This typically indicates a myQ API lockout for a 60-90 minute period before resuming API connectivity.
```

**To Reproduce:**
1. Install the plugin
2. Run it on a bridge
3. Observe logs

**Logs:**
```
myQ API error: Temporary myQ API server-side issues encountered: 429 - Too Many Requests. This typically indicates a myQ API lockout for a 60-90 minute period before resuming API connectivity.
```

**Homebridge Configuration:**

```json
{
    "platform": "myQ",
    "email": "email",
    "password": "password"
}
```

**Screenshots:**
N/A

**Environment:**

* **Homebridge Version:** 1.6.0
* **Node Version:** 16.19.1
* **Homebridge-myQ Plugin Version**: 3.4.3
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** IPhone IOS 17
* **Operating System and OS Version:** Not sure what in relation to? Im using the Hoobs box

**Comment by Wheemer** [comment]
Thank you for reporting properly.

I am experiencing the exact same thing.

**Comment by cooperz** [comment]
I've tried disabling the plugin overnight and just re-enabling this morning. They must have changed something again in the API / URL formatting.

**Comment by BrendanGrant** [comment]
The rate limiting is far from a surprise. When last I looked into how often this plugin (via HB requests IIRC) was querying, it was something on the order of once per second... which is fantastic for knowing the exact state of your door at anytime, but is pretty wasteful and creating a needless load on their infrastructure.

It would be nice if they would incorporate information on how much is too much so that we as users, either of this plugin or other software can know how often is ok to query.

To try to stay off their radar, I'd built my own client/service which would call into MyQ every hour to check on the status of all of my doors (4 on one account), and order the closing of any which had been open for more than an hour.

**Comment by hjdhjd** [comment]
Thanks for the report. This has been asked and answered - I’ve got nothing further to provide here. If you have multiple myQ integrations, you might want to disable them all for a few hours given they may be locking themselves out as well. The plugin works for the majority of folks - but I recognize you might be having issues. There is nothing more to be said or done here. I will be locking this thread as well, but leaving it pinned for folks.

My advice:

Disable any/all myQ integrations whether it’s mine or any other for several hours if you’re having an issue.
If you’re unsure: change your myQ password to definitively ensure you aren’t inadvertently generating them.
Try again the next day with HBMQ (homebridge-myq) and see if things work.

Beyond that, there’s not much to do here - we do the best we can with the API we have. It’s unsatisfying, but that’s the way it is in myQ land.

Also, a more general note to others who come across this: understand that I am one person providing something out of my free time and supporting a community I love. Remarks about how “aggressive” the support template is, or how I choose to provide support for something everyone benefits from is impolite to say the least. Please respect how I choose to provide support. You’re not the one dealing with the support deluge requests for something everyone seems to feel an entitlement toward. 😄 Please have some empathy and respect.

This is not a forum for discussion, this is a specific support channel for specific issues. If you’d like to do that, the Discord myQ channel is the place to go…there’s a lot of good dialog, and we’re a reasonably active community.

**Comment by hjdhjd** [comment]
@BrendanGrant and @ryanlindsey - while well-intentioned, I am sure, I deleted your remarks because they will continue to cause confusion as to the nature of the myQ issues. I’ve stated these elsewhere, but once more:

1. This is not a rate limiting issue, though it may appear that way. Look at the links below for more context.
2. No, HBMQ does not poll once per second in a regular state and never has.
3. This isn’t about “staying off the radar”. This is an intentional move by myQ to further constrain access.

More context for the curious:
https://github.com/hjdhjd/homebridge-myq/issues/1126#issuecomment-1763476073
https://github.com/hjdhjd/homebridge-myq/issues/1125#issuecomment-1763475185
