### ISSUE TITLE
Repaired my garage door now can't readd to homebridge

### ISSUE THREAD

**Issue by kbrashears5** [hjdhjd/homebridge-myq#121]
**Describe The Problem:**

Re-paired my garage door after moving to new house. Didn't work in HomeKit so I removed the bridge and tried to readd it. Now I can't get the bridge back by manually entering the HomeKit code. HomeBridge can see the changes as the logs report that the garage door is closed. So long story short the issue is I can't add the bridge manually via the code
**To Reproduce:**

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version**: 
* **Homebridge myQ Version**:
* **Operating System and OS Version**:

**Comment by hjdhjd** [comment]
Congrats on the new house!

As to your issue...usually, it's something in how you're trying to add it in the Home app.

I'd suggest posting this issue to the Homebridge issues page or the Discord. This doesn't look like a plugin-specific issue. Your issue seems to be getting Homebridge paired with HomeKit.

Good luck!

**Comment by kbrashears5** [comment]
finally was able to look at this again - solution was to remove the `accessories` and the `persist` folders in my homebridge directory, then restart my homebridge instance. It must have been caching something to the old bridge, preventing me from adding the new.
