### ISSUE TITLE
400 error

### ISSUE THREAD

**Issue by mbierman** [hjdhjd/homebridge-myq#144]
**Describe The Problem:**
I'm getting the following errors. Is anyone else having any issues?

**To Reproduce:**
1. Install the plugin. 
1. Restart Homebridge. 
1. check Terminal. 

**Logs:**
```
myQ API: Error: 400 Bad Request
[10/19/2020, 2:09:37 AM] [myQ] myQ API: Unable to authenticate. Will retry later.
```

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
        {
            "email": "XXXt",
            "password": "XXX",
            "platform": "myQ"
        }
```

**Screenshots:**

**Environment:**

* **Homebridge Version**: 1.1.6
* **Node Version:** 12.18.4
* **Homebridge-myQ Plugin Version**: 2.3.2
* **Apple Device(s)**: iphone 6s ios and iPad 7 14.0.1
* **Operating System**: Docker
* **Process Supervisor**: Docker

**Comment by mbierman** [comment]
Two pieces of information. I have a dual WAN set up with 80% of traffic going to one isp and 20% going to another for backup. When I deactivate the secondary ISP things seem to work. I've told MyQ about this. 

Second, I see this in this plugins logs: 

`myQ API: throttling acquireSecurityToken API call.`

even though I have set the highest thresholds the settings allow.

**Comment by hjdhjd** [comment]
Thanks for the report. Throttling the security token API call is not a bug, it’s working as intended.

You seem to have identified your root cause - namely that you’re not going out on the same IP address every time. This isn’t a myQ plugin issue. I believe it’s a security feature of the myQ API server endpoints - they don’t like it when you switch IP addresses on an authorized security token.

The fix: stop using separate IP addresses on the outbound. 😄 There’s not much else I can do on this one I’m afraid, and you seem to have diagnosed the crux of the problem already.

myQ will not fix this on their end, if history is an indicator. Frankly, I’d get if their perspective that this isn’t even a bug as they see it.

Best of luck.

**Comment by mbierman** [comment]
I only mentioned API throttling because I was getting messages that suggested the plugin was being too aggressive and needed to backoff. That was probably because of the errors being thrown. 

I agree, the Plugin can't reasonably control the IPs and that the changes in IPs seem to trigger a negative response from MyQ.

It is unfortunate to have to turn off the load balancing but you are right, until my router (Firewalla) implement PBR, I can't control what traffic goes on what WAN either. This causes havoc with Hulu as well so hopefully they will get to it sooner than later. 

Anyway, I agree nothing I can imagine you being able to do here to fix so I'll close this. Thank you.
