### ISSUE TITLE
Requesting support for Low Battery Warning

### ISSUE THREAD

**Issue by MikeThomas123456** [hjdhjd/homebridge-myq#369]
**Is your feature request related to a problem? Please describe:**
No specific problem other than warning in log that the context is not supported

**Describe the solution you'd like:**
Homebridge-myq doesn't seem capable of supporting the low battery warning as generated from the MyQ "add-on" kit.

The following message is displayed in the Homebridge log for this plug-in
[homebridge-myq] This plugin generated a warning from the characteristic 'Status Low Battery': Characteristic not in required or optional characteristic section for service GarageDoorOpener.

**Describe alternatives you've considered:**
Right now, home bridge just ignores the warning and I rely on the MyQ app to report the battery warnings.

**Additional context:**
n/a

**Comment by hjdhjd** [comment]
Thanks for the report. The warning is a non-issue and has nothing to do with whether it works or not. :smile: The warning you see is because I've added a characteristic to support this to the plugin and it's not a standard part of what HomeKit expects, though it works just fine. I appreciate why one might think they're related, but assuredly, they are **not**. It's a warning, and while technically correct, it's ultimately meaningless in this instance.

If it provably isn't working, it would be an artifact of the shift to the new myQ API a few months ago, and I'll take a look.
