### ISSUE TITLE
Looking for V6 request format to operate a door

### ISSUE THREAD

**Issue by colinrblake** [hjdhjd/homebridge-myq#583]
This isn't a bug, but a request for some information on how to operate the garage door using V6.

Background. I have my own iOS code which worked fine for V5. Thanks to this project I managed to get my code working against V6. I can now login, get my accountId and my devices. However, I can not open or close the garage door. 

I am looking for information on what the V6 format of the "actions" PUT request is. Can anyone help?

**Comment by colinrblake** [comment]
In case anyone else is looking for this, I found the answer in the pymyq code:

`https://account-devices-gdo.myq-cloud.com/api/v5.2/Accounts/{account_id}/door_openers/{device_serial}/{command}`

where command is "open" or "close". The method is PUT.

**Comment by hjdhjd** [comment]
Take a look the myQ library I made available rather than rolling your own, if you’re interested: https://github.com/hjdhjd/myq

pymyq and others have leveraged it for their own implementations as well. We’re trying to consolidate where it makes sense to get everyone operating off the same implementation rather than recreating the proverbial wheel too many times. :smile:

**Comment by colinrblake** [comment]
@hjdhjd Well now I feel dumb. I looked again at your myQ library and the door open/close code is there. Not sure how I missed it when I was using your code as a reference to implement the new OAuth login sequence for my iOS app.
