### ISSUE TITLE
"Invalid myQ Credentials Given (even though they're valid)

### ISSUE THREAD

**Issue by kylethedarling** [hjdhjd/homebridge-myq#641]
**Describe The Problem:**
Hi, new user who would really appreciate some help.
I install the plugin, add my email and password, but logs show that credentials are wrong even though they are not.

Running HOOBS on a PI 3 B+
homebridge-myq version 2.7.4

Thanks for keeping this project going.

**To Reproduce:**
To reproduce I just start the plugin and check the logs.

**Logs:**

2/14/2022, 1:26:17 AMmyQ Bridge starting
2/14/2022, 1:26:27 AMmyQ BridgeLoaded plugin 'homebridge-myq'
2/14/2022, 1:26:27 AMmyQ BridgeLoading 1 platforms...
2/14/2022, 1:26:27 AMmyQ BridgeBridge is running on port 51826.
2/14/2022, 1:26:28 AMmyQ BridgemyQERRORmyQ API: Invalid myQ credentials given. Check your login and password.
2/14/2022, 1:28:28 AMmyQ BridgemyQERRORmyQ API: Invalid myQ credentials given. Check your login and password.
2/14/2022, 1:30:29 AMmyQ BridgemyQERRORmyQ API: Invalid myQ credentials given. Check your login and password.

**Homebridge Configuration:**
homebridge 1.4.0
HOOBS 4.1.22

**Screenshots:**
n/a

**Environment:**

* **Homebridge Version:** 1.4.0
* **Node Version:** 16.14.0
* **Homebridge-myQ Plugin Version**: 2.7.4
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone 13 Pro Max iOS 15.4
* **Operating System and OS Version:** HOOBS 4.1.22

**Comment by bamodio** [comment]
This issue is still active. Shouldn't be closed. Not specific to new users.

It's a regression from previous valid logins, and it might be happening for a few weeks now. Did myQ APIs change again?

**Comment by hjdhjd** [comment]
I appreciate that you're having issues, but it's not a regression in the API. The API is working correctly. There's some issue related to your login credentials. I don't support HOOBS directly, so you're a bit on your own there...but there aren't widespread issues here. I'd try the panoply of things people have tried in similar situations, perhaps starting with doing a password reset and seeing if it helps. 

There isn't a plugin issue here to resolve that I can see other than it's not working for you when it previously was...unfortunately, that's not much to go on, particularly since no meaningful changes have happened on either the plugin end or the API end (to the extent I can see in any case). Best of luck.

**Comment by dwwhalen** [comment]
Just FYI....I was having this issue and it was user error on my part.  I assumed that the id/pw to use was the MyQ web portal id/pw.  That appears to be incorrect. It actually wants that id/pw used to sign into the MyQ mobile app.  Once I entered that and restarted all was good.  Also, you may need to reset your password if you exceeded max login attempts using the wrong pw.
