### ISSUE TITLE
Constant DNS requests to accounts.myq-cloud.com and devices.myq-cloud.co

### ISSUE THREAD

**Issue by mgrimace** [hjdhjd/homebridge-myq#755]
**Describe The Problem:**
PiHole is showing constants DNS requests to both accounts.myq-cloud.com and devices.myq-cloud.com, approximately 3+ calls every 15 seconds.

**To Reproduce:**
Run the plugin

**Logs:**
Occassionally shows the following error too:

```
[6/18/2022, 11:44:50 AM] [myQ] request to https://accounts.myq-cloud.com/api/v6.0/accounts failed, reason: getaddrinfo EAI_AGAIN accounts.myq-cloud.com
[6/18/2022, 11:44:51 AM] [myQ] myQ API: Unable to retrieve account information.
```

**Scre
<img width="431" alt="Screen Shot 2022-06-18 at 2 35 19 PM" src="https://user-images.githubusercontent.com/55518507/174451962-09b850f5-ca87-43a7-a7ca-687099503649.png">
enshots:**

**Environment:**

* **Homebridge Version:** v1.4.1
* **Node Version:** v16.15.1
* **Homebridge-myQ Plugin Version**: v2.7.4
* **Operating System and OS Version:** Raspberry Pi Zero 2W, Docker, Raspberry Pi OS lite 64-bit, v11

**Comment by hjdhjd** [comment]
Thanks for the report - this is normal and expected behavior. The myQ API is queried every 10-15 seconds.

**Comment by mmaetzler** [comment]
@hjdhjd Can that query interval be configured in some way? In my network, the Homebridge-myQ Plugin is by far the most talkative item, outperforming the second device (a very talkative amazon IOT device) by 10x.

**Comment by mmaetzler** [comment]
I guess it's the `Refresh Interval` under `Advances Settings`?

**Comment by hjdhjd** [comment]
It is, but changing the settings will impact the granularity of the plugin. Bottom line: this plugin polls the API regularly. If you don't want to poll the API regularly, knock yourself out, but you **will** miss open and close events if you do so. It's up to you. I remain curious why anyone cares...if you care this much, you're better off not using any unofficial plugin for this and just buying the Liftmaster / Chamberlain hardware.

Cheers.

**Comment by mmaetzler** [comment]
> I remain curious why anyone cares

Please don't get me wrong, I'm forever grateful for all work that you and other plugin creators. And like you said, whoever changes the default values operates at their own risk, a notion I totally agree with. I just wanted to add some color why the DNS request question comes up here and there, so here I go:

In my case, I control (and rate limit / block) devices and software in my network. I currently have 43 devices with an IP address that connect to the internet for various reasons. For my use case, the garage door plugin is a _toy_, nothing that makes or breaks my day. Having said that, I do not want that _toy_ (in the way I use homebridge) to be the number 1 DNS request sender across 43 devices, outperforming number 2 by 10x in daily requests. Not that my Pi-Hole and router cannot handle those requests. I was just asking myself _"do I really rely on my garage opener plugin that much that it needs to be the most talkative thing in my network?"_.

Again, the default values make sense for most users. For my use case, I have now modified the `Refresh Interval`.

**Comment by hjdhjd** [comment]
Appreciate the insight!

I still genuinely do not understand why anyone **cares** how many DNS requests any particular tool makes, provided it isn’t conducting a DoS attack or misbehaving in some way, of course. Why does it matter that the proverbial toy is the number one (or number 90 for that matter) generator of DNS requests on a home network? It’s rounding error in the grand scheme of things.

Idle curiosity - completely get that. 😄 Curiosity is what led me to reverse engineering the API and creating the plugin and API library! 

Concern relative to other devices on the network - I just don’t follow why anyone spends that much time looking at the number of DNS queries on their network by device/app. 😄 Glad `homebridge-myq` is number one I guess? 😉 What I still don’t follow is **why care**? It’s a stat in a log somewhere and shouldn’t meaningfully impact anything else other than curious people who seem to enjoy keeping DNS stats…  

I also get that we’re all particular people, and people like their networks the way they like their networks - I know I sure do - which is why I find the inquiries on this topic so fascinating.

Measuring what requests this plugin makes against something other IoT devices is a bit of apples-and-baseballs comparison. They’re not even in the same category API-wise - most of the IoT devices out there are either devices from the maker in question, or (hopefully) something with a documented API that doesn’t need to be polled regularly for status. myQ is far from a decent protocol/API…it’s just useful enough to do things like this plugin…but it’s an inefficient mess of a protocol until they come up with something more modern that doesn’t force us to poll regularly for status. But I digress…back to apples and baseballs…most things out there in the IoT world operate in some sort of a pub/sub “I will get information pushed to me to let me know something interesting has happened”. There’s just not a lot of stuff in the IoT/automation space left that’s quite like myQ these days…and that’s for the better. Hope the day comes when we can get a modern myQ API to work with!

A heartfelt thank you for shedding a little light on your interest in the topic…I hope you take the above with the humor and amusement that I intended to infuse it with.
